open ElfCalories
open RockPaperScissors
open Rucksack
open CampCleanup
open SupplyStacks
open TuningTrouble

getDay1Solution
getDay2Solution
getDay3Solution
getDay4Solution
getDay5Solution
getDay6Solution
